MHub / GC - Add the Node21 baseline model
MHubAI/models pull request #41
Opened 2023-08-02 15:42 UTC by silvandeleemput

This PR adds the GC STOIC baseline model (from the [STOIC2021 challenge](https://stoic2021.grand-challenge.org/)) to MHub.
GitHub Repo: https://github.com/node21challenge/node21_detection_baseline
GC page: https://node21.grand-challenge.org/

### Algorithm I/O
  * Input should be a Lung X-Ray image (MHA) (This MHub implementation expects a Dicom which is converted to MHA using panimg MhaConverter)
  * Outputs are:
    * A JSON file with the bounding boxes and probabilities for the nodules
  * Test DICOM images for this algorithm can be downloaded from IDC:
 ```
# To download the files in this manifest, first install s5cmd (https://github.com/peak/s5cmd),
# then run the following command:
# s5cmd --no-sign-request --endpoint-url https://storage.googleapis.com run file_manifest_gcs.s5cmd
cp s3://public-datasets-idc/8fb5dfd4-0bd1-4dc2-a8a7-7a867c40450e/* .
cp s3://public-datasets-idc/3c0bd6df-1772-4bb2-abe5-570665311253/* .
```

### Caveats
* I added the `CR = Meta(mode="CR")       # CR	Computed Radiography` label, which should move to `mhubio/core/templates.py`, not really sure if this is the best label for Chest X-Rays (CXR)
* The PR target is `main`, but should be something like `m-gc-node21-baseline`
* In the Dockerfile the MHub model repo integration is currently marked `TODO` and should be uncommented/edited
* Added a TODO to the `MHAConverter` since it doesn't have the `panimg` backend yet (without this backend it fails for my test image), and it uses a `run.py` script to use the panimg mhaconverter.

2023-09-14 14:05 UTC, silvandeleemput commented
Updated this PR:
* Dockerfile
  * Use mhubio.run as entrypoint
  * Fixed commit for node21 repo
  * Updated TODO on MHub model code integration
* default.yml
  * Changed mhaconverter backend to panimg
* Node21BaselineRunner.py
  * Added comments
* Removed
  * run.py
  * PanImgConverters.py

2023-11-22 11:30 UTC, LennyN95 commented
_**NOTE**: This PR proposes a model currently using a dynamic length output. We are working on a method to export dynamic length outputs and will likely introduce a `@IO.Out.Data.Many` decorator (similar to our `@IO.Output` -> `@IO.Outputs` decorators)._

2023-11-23 13:49 UTC, LennyN95 commented on models/gc_node21_baseline/utils/Node21BaselineRunner.py
> +    @IO.Output('out_data', 'nodules.json', 'json:model=Node21Baseline', 'in_data', the='Node21 baseline nodule prediction')
In addition to the original file output (which should always be accessible to reproduce the original pipeline as-is) we need to include the value-based findings via the `@IO.OutputData(s)` decorator to make these values accessible to our ReportExporter (and thereby allowing a standardized output structure).

2023-11-23 20:05 UTC, silvandeleemput commented on models/gc_node21_baseline/utils/Node21BaselineRunner.py
> +    @IO.Output('out_data', 'nodules.json', 'json:model=Node21Baseline', 'in_data', the='Node21 baseline nodule prediction')
That seems fine, does it have to be implemented using the `@IO.Out.Data.Many` decorator or is `@IO.OutputData(s)` sufficient? Do you maybe have an example of how it works?

2023-11-23 20:27 UTC, silvandeleemput commented on models/gc_node21_baseline/utils/Node21BaselineRunner.py
> +    @IO.Output('out_data', 'nodules.json', 'json:model=Node21Baseline', 'in_data', the='Node21 baseline nodule prediction')
A small example of the JSON output by the model:

```json
{
    "type": "Multiple 2D bounding boxes",
    "boxes": [
        {
            "corners": [
                [
                    274.9,
                    224.49,
                    0
                ],
                [
                    258.17,
                    224.49,
                    0
                ],
                [
                    258.17,
                    206.72,
                    0
                ],
                [
                    274.9,
                    206.72,
                    0
                ]
            ],
            "probability": 0.44
        },

        {
            "corners": [
                [
                    315.46,
                    266.54,
                    0
                ],
                [
                    292.71,
                    266.54,
                    0
                ],
                [
                    292.71,
                    239.46,
                    0
                ],
                [
                    315.46,
                    239.46,
                    0
                ]
            ],
            "probability": 0.08
        },
    ],
    "version": {
        "major": 1,
        "minor": 0
    }
}

```

2023-11-24 11:47 UTC, LennyN95 commented on models/gc_node21_baseline/utils/Node21BaselineRunner.py
> +    @IO.Output('out_data', 'nodules.json', 'json:model=Node21Baseline', 'in_data', the='Node21 baseline nodule prediction')
The second example here will be the most relevant to your use-case: https://github.com/MHubAI/documentation/blob/main/documentation/mhubio/how_to_write_an_mhubio_module.md#dynamic-output-1n

If you want to export the bounding box plus probability, you must define 4*3+1 value outputs. 
This is one of the edge cases, so instead suggest we discuss the format. n MHub-specific `Coordinate` datatype with additional parameters could be a solution. The problem I see with plain floating point coordinates is, that when comparing multiple algorithms the individually used reference frames might be different and the coordinates thus are not directly comparable.

So for now, a single ValueOutput for the probability risk can be used.

In the near future, we'll rename all decorators to a more straightforward naming schema. You can stick to the old syntax for now, we'll patch all implemented models once this becomes effective.
```
@IO.Input       -> @IO.In.File.One
@IO.Inputs      -> @IO.In.File.Many
@IO.Output      -> @IO.Out.File.One
@IO.Outputs     -> @IO.Out.File.Many
@IO.OutputData  -> @IO.Out.Data.One
@IO.OutputDatas -> @IO.Out.Data.Many
```

2023-11-24 21:54 UTC, silvandeleemput commented on models/gc_node21_baseline/utils/Node21BaselineRunner.py
> +    @IO.Output('out_data', 'nodules.json', 'json:model=Node21Baseline', 'in_data', the='Node21 baseline nodule prediction')
Thanks for the explanation! I stick to your suggestion for a single ValueOutput for now.

2023-11-25 08:27 UTC, LennyN95 commented on models/gc_node21_baseline/utils/Node21BaselineRunner.py
> +    @IO.Output('out_data', 'nodules.json', 'json:model=Node21Baseline', 'in_data', the='Node21 baseline nodule prediction')
I was thinking about it. Let's do two. One for the probability, type float. And one for the bounding box type str. 
Then add `Meta(format='json')` besides any other metadata to the bounding box type. 
Encoding the bounding boxes as JSON strings is yet flexible and can be fully explained in the description. 

Some questions:
In what reference frame are the coordinates? 
Does any re-sampling happen of the image?

2024-04-18 11:08 UTC, silvandeleemput commented on models/gc_node21_baseline/utils/Node21BaselineRunner.py
> +    @IO.Output('out_data', 'nodules.json', 'json:model=Node21Baseline', 'in_data', the='Node21 baseline nodule prediction')
I implemented your suggestion. 

Regarding the questions:
Looking at the source code there appears to be no re-sampling of the input image. 
The bounding box coordinates are apparently in mm counting from the top-left corner of the image.

2024-04-18 11:36 UTC, silvandeleemput commented
[gc_node21_baseline_output.zip](https://github.com/MHubAI/models/files/15024198/gc_node21_baseline_output.zip)

2024-04-18 11:36 UTC, silvandeleemput commented
/test

```yaml
sample:
  idc_version: 17.0
  data:
    - SeriesInstanceUID: 1.3.6.1.4.1.14519.5.2.1.6279.6001.210102868760281756294235082201
      aws_url: s3://idc-open-data/b1c859c3-7471-43e7-9882-0bb5420ec18a/*
      path: dicom

reference:
  url: https://github.com/MHubAI/models/files/15024198/gc_node21_baseline_output.zip
```

2024-04-18 11:39 UTC, silvandeleemput commented
/review

We updated the meta.json file, we implemented the suggestion for the OutputDatas (probabilities, and bounding boxes as JSON), and we have wrapped the algorithm/model in a CLI to avoid stdout capture issues. It should be as good as done, please have a look.

2024-04-18 11:41 UTC, LennyN95 approved these changes

2024-04-19 06:56 UTC, LennyN95 reviewed
To keep the structure clean, the `utils` folder ideally only contains any MHub-IO related utilities (e.g., custom Modules such as the Node21BaselineRunner) but no model implementation code. All model implementation should go into an `src` folder, all additional resources into an `res` folder. 

Making such a change is purely organizational (although for the utils folder, it is somewhat meaningful as we parse this folder to detect available Modules).

However, in case you have to make any code adjustments and we have to redo the test, I'd ask for this change.

2024-04-19 06:58 UTC, LennyN95 requested changes
The test failed and showed (high) variation in the bounding boxes. This needs to be investigated before we can proceed.

2024-04-23 13:34 UTC, silvandeleemput commented
I investigated this issue and found the root cause for the large bounding box differences.

Rerunning on my machine consistently gave me the same output as I have uploaded before.
I have 5 detected nodules with each 4 corners (3 values x,y,z=0) and a probability.

Comparing these with your test results I found:
- The number of detected bounding boxes matches the number I found on my side (5). This seems ok.
- All found probabilities match pretty closely. (some small deviations are expected because of GPU hardware/driver differences and rounding errors). These seem fine.
- Bounding boxes 0, 1, and 4 seem fine and the same as what I found.
- Bounding boxes 2 & 3 are swapped, having the same probability! Giving rise to the big found differences. It seems to be a sorting issue.

I can fix this by applying a better sorting algorithm after the output is generated to produce a more consistent output JSON file. This can be added to the cli.py and go together with a small refactor of the cli.py file to a /src directory. This should be under `/models/gc_node21_baseline/src/` then ?

2024-04-24 08:14 UTC, silvandeleemput commented
@LennyN95 alright, I have added the improved sorting, moved the cli.py to a src directory, and updated the model version to 1.1, both in the meta.json and the Dockerfile. The previous test can be redone and should produce better results because the sorting issue is fixed. This model should be as good as done.

2024-04-25 09:26 UTC, silvandeleemput commented
I looked at the new result generated after adding the sorting fix, and the sorting works now: the same bounding boxes are found and sorted in the correct order. The found differences this time around are only small rounding errors for both the coordinates of the bounding boxes and for the probabilities, which are expected. This result is acceptable.

2024-04-25 12:05 UTC, LennyN95 approved these changes
Test passed (rounding errors expected, see comment from the model contributor).

2024-04-25 12:05 UTC, merged